DROP TABLE IF EXISTS medicine;
DROP TABLE IF EXISTS account;
create table medicine
(
    medicine_id          bigint       not null
        primary key,
    create_date          timestamp,
    last_modified        timestamp,
    class_name           varchar(50),
    class_no             varchar(10),
    etc_otc_name         varchar(100),
    item_image           varchar(500),
    item_name            varchar(200) not null,
    item_seq             bigint       not null,
    leng_long            varchar(50),
    leng_short           varchar(50),
    thick                varchar(50),
    mark_code_back_anal  varchar(100),
    mark_code_back_img   varchar(500),
    mark_code_front_anal varchar(100),
    mark_code_front_img  varchar(500),
    color_back           varchar(100),
    color_front          varchar(100),
    entp_name            varchar(100),
    entp_seq             bigint,
    change_date          date,
    img_regist_ts        date,
    item_permit_date     date,
    chart                varchar(500),
    drug_shape           varchar(50),
    form_code_name       varchar(50),
    print_back           varchar(50),
    print_front          varchar(50),
    line_back            varchar(3000),
    line_front           varchar(3000)
);

create table account
(
    account_id    bigint generated by default as identity
        primary key,
    create_date   timestamp,
    last_modified timestamp,
    email         varchar(255) not null,
    gender        varchar(255) not null,
    name          varchar(255) not null,
    password      varchar(255) not null,
    role          varchar(255) not null,
    status        varchar(255) not null
);



