drop table if exists batch_job_execution_params;

drop table if exists batch_step_execution_context;

drop table if exists batch_step_execution;

drop table if exists batch_job_execution_context;

drop table if exists batch_job_execution;

drop table if exists batch_job_instance;

drop table if exists alarm_medicine_alarms;

drop table if exists bookmark;

drop table if exists medicine_alarm;

drop table if exists alarm;

drop table if exists account;

drop table if exists medicine;




create table batch_job_instance
(
    job_instance_id bigint       not null
        primary key,
    version         bigint,
    job_name        varchar(100) not null,
    job_key         varchar(32)  not null,
    constraint job_inst_un
        unique (job_name, job_key)
);


create table batch_job_execution
(
    job_execution_id           bigint    not null
        primary key,
    version                    bigint,
    job_instance_id            bigint    not null
        constraint job_inst_exec_fk
            references batch_job_instance,
    create_time                timestamp not null,
    start_time                 timestamp,
    end_time                   timestamp,
    status                     varchar(10),
    exit_code                  varchar(2500),
    exit_message               varchar(2500),
    last_updated               timestamp,
    job_configuration_location varchar(2500)
);

create table batch_job_execution_params
(
    job_execution_id bigint       not null
        constraint job_exec_params_fk
            references batch_job_execution,
    type_cd          varchar(6)   not null,
    key_name         varchar(100) not null,
    string_val       varchar(250),
    date_val         timestamp,
    long_val         bigint,
    double_val       double precision,
    identifying      char         not null
);


create table batch_step_execution
(
    step_execution_id  bigint       not null
        primary key,
    version            bigint       not null,
    step_name          varchar(100) not null,
    job_execution_id   bigint       not null
        constraint job_exec_step_fk
            references batch_job_execution,
    start_time         timestamp    not null,
    end_time           timestamp,
    status             varchar(10),
    commit_count       bigint,
    read_count         bigint,
    filter_count       bigint,
    write_count        bigint,
    read_skip_count    bigint,
    write_skip_count   bigint,
    process_skip_count bigint,
    rollback_count     bigint,
    exit_code          varchar(2500),
    exit_message       varchar(2500),
    last_updated       timestamp
);


create table batch_step_execution_context
(
    step_execution_id  bigint        not null
        primary key
        constraint step_exec_ctx_fk
            references batch_step_execution,
    short_context      varchar(2500) not null,
    serialized_context text
);


create table batch_job_execution_context
(
    job_execution_id   bigint        not null
        primary key
        constraint job_exec_ctx_fk
            references batch_job_execution,
    short_context      varchar(2500) not null,
    serialized_context text
);


create table account
(
    account_id    bigint generated by default as identity
        primary key,
    create_date   timestamp,
    last_modified timestamp,
    email         varchar(255) not null,
    gender        varchar(255) not null,
    name          varchar(255) not null,
    password      varchar(255) not null,
    role          varchar(255) not null,
    status        varchar(255) not null
);


create table alarm
(
    alarm_id             bigint generated by default as identity
        primary key,
    create_date          timestamp,
    last_modified        timestamp,
    deleted              boolean      not null,
    deleted_at           timestamp,
    dose_count           integer      not null,
    left_over_dose_count integer      not null,
    title                varchar(255) not null,
    account_id           bigint       not null
        constraint fke03rmlyu080erup7c0w711ut3
            references account
);


create table medicine
(
    medicine_id          bigint generated by default as identity
        primary key,
    create_date          timestamp,
    last_modified        timestamp,
    class_name           varchar(50),
    class_no             varchar(10),
    etc_otc_name         varchar(100),
    item_image           varchar(500),
    item_name            varchar(200) not null,
    item_seq             bigint       not null,
    leng_long            varchar(50),
    leng_short           varchar(50),
    thick                varchar(50),
    mark_code_back_anal  varchar(100),
    mark_code_back_img   varchar(500),
    mark_code_front_anal varchar(100),
    mark_code_front_img  varchar(500),
    color_back           varchar(100),
    color_front          varchar(100),
    entp_name            varchar(100),
    entp_seq             bigint,
    change_date          date,
    img_regist_ts        date,
    item_permit_date     date,
    chart                varchar(500),
    drug_shape           varchar(50),
    form_code_name       varchar(50),
    print_back           varchar(50),
    print_front          varchar(50),
    line_back            varchar(3000),
    line_front           varchar(3000)
);

create table bookmark
(
    bookmark_id   bigint generated by default as identity
        primary key,
    create_date   timestamp,
    last_modified timestamp,
    created_by    varchar(255),
    updated_by    varchar(255),
    account_id    bigint
        constraint fkdld3dxpefeqpr9rxyef5idjg4
            references account,
    medicine_id   bigint
        constraint fkb9uiy4go5pwupe71ix5hlgotv
            references medicine
);


create table medicine_alarm
(
    medicine_alarm_id bigint generated by default as identity
        primary key,
    create_date       timestamp,
    last_modified     timestamp,
    alarm_id          bigint not null
        constraint fk6s8dt1ynatx4phid05yt89en6
            references alarm,
    medicine_id       bigint not null
        constraint fkr1ch6jbf602mstegm5eyogo26
            references medicine
);


create table alarm_medicine_alarms
(
    alarm_alarm_id                    bigint not null
        constraint fk45jr7gnet8cl7du6bm35cj9t4
            references alarm,
    medicine_alarms_medicine_alarm_id bigint not null
        constraint uk_g4dn9bogjbf826kqg5x8kt2ef
            unique
        constraint fk7186y3x8dse8hbr64kaef8cse
            references medicine_alarm
);



